/**
 * @packageDocumentation
 * Shared fast-check run configuration for property-based test suites.
 */

type FastCheckAssertConfiguration = Readonly<{
    numRuns: number;
}>;

const defaultFastCheckRunCount = 70 as const;
const generatedIdentifierPattern = /^[A-Z_a-z]\w{0,8}$/v;

const reservedEcmascriptIdentifierNames = new Set<string>([
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
]);

/**
 * Checks whether a generated token is safe to embed as an ECMAScript
 * identifier.
 *
 * @param candidate - Potential identifier token generated by fast-check.
 *
 * @returns `true` when the candidate matches identifier syntax and is not a
 *   reserved language keyword.
 */
export const isSafeGeneratedIdentifier = (candidate: string): boolean =>
    generatedIdentifierPattern.test(candidate) &&
    !reservedEcmascriptIdentifierNames.has(candidate);

/**
 * Prebuilt `fc.assert(..., options)` objects.
 */
export const fastCheckRunConfig: Readonly<
    Record<"default", FastCheckAssertConfiguration>
> = {
    default: {
        numRuns: defaultFastCheckRunCount,
    },
};
