import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Main sidebar configuration for the primary documentation section. */
const sidebars = {
    docs: [
        {
            id: "developer/index",
            label: "Developer Docs",
            type: "doc",
        },
        {
            id: "developer/docusaurus-site-contract",
            label: "🧭 Docs Site Contract",
            type: "doc",
        },
        {
            collapsed: false,
            items: [
                {
                    dirName: "developer/api",
                    type: "autogenerated",
                },
            ],
            label: "📘 API",
            link: {
                description:
                    "Generated API documentation for the plugin runtime and internal helpers.",
                title: "API",
                type: "generated-index",
            },
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
